### ISSUE TITLE
OFL?

### ISSUE THREAD

**Issue by davelab6** [rubjo/victor-mono#120]
Would you consider switching the license to the font-specific OFL, and making the font available in Google Fonts?

OFL has benefits over MIT such as no requirements on documents that embed the font - strictly it seems to me, IANAL, that this is required by MIT.

**Comment by rubjo** [comment]
Yeah, I’ve noticed that most open fonts use that license instead of MIT, although I’ve never really tried to learn why. If what you’re saying is correct and OFL is just more permissible in *every* aspect, I can probably just switch to that for the next release.

Google Fonts:
Per https://github.com/google/fonts/blob/main/CONTRIBUTING.md
it looks like some work is required to make a submission pass - that’s work I don’t have time for at the moment.

**Comment by davelab6** [comment]
The GF team can do some or all of that work, and we're not in a rush :) The
main practical thing aside from license would be minimum glyph set, but we
are actively developing a new smaller minimum which you likely already
cover.

The OFL is not more permissible in every aspect, the main difference is
that it requires derivatives to also be OFL. However, it doesn't make any
requirements of you or anyone to provide sources. It has an option to
require modifications to be renamed, but you don't have to use that option,
and GF prefers it not be used.

**Comment by rubjo** [comment]
Sure, I’ll definitely consider this once I catch up on some other projects going on at the moment.

I seem to recall skimmimg through the rather wordy Google Fonts submission requirements list at some point last year and thinking nah maybe later after seeing that requirement about font set, yes. :)

**Comment by rubjo** [comment]
License is changed to OFL from latest release onwards.
