### ISSUE TITLE
Font suggestion

### ISSUE THREAD

**Issue by Danovich** [rubjo/victor-mono#14]
First of all I love the font, great work 👍

Can I suggest changing the <= and >= to be with a flat bottom line?
![notAngled](https://user-images.githubusercontent.com/26672793/60421753-1d278c00-9bf3-11e9-96f5-3db955db93c8.jpg)
And maybe changing the 'I' and 'T' in italics?
![betterIandT](https://user-images.githubusercontent.com/26672793/60421860-5b24b000-9bf3-11e9-8f81-ff46418142f5.jpg)

**Comment by rubjo** [comment]
Thanks for the kind words! :)

### <= and >=
I'm inclined to keep these as is for the time being. The gap between the lines is considerably larger than the Fira version, so I think it's pretty hard to miss the difference compared to a normal < or >, even at small sizes.
![Skjermbilde 2019-07-01 kl  10 53 18](https://user-images.githubusercontent.com/42270947/60424059-c3719280-9bef-11e9-911b-c955f5c886e4.png)

### Italic i and t
Agreed, using the l-style foot for these didn't really work. They are already revised, try to download and reinstall.

**Comment by kiliman** [comment]
Ha, looks like @Danovich used my screenshots from Twitter.

First of all, just wanted to say awesome job on this font. I wrote a tool to add ligatures to Operator Mono (https://github.com/kiliman/operator-mono-lig), so I know the hard work that goes into making a font, let alone creating the italic versions.

Since my tool has to literally build a font by modifying an existing font (since OM is not free), I added the ability to customize which ligatures (and alternate glyphs) to add or remove from the final font.

BTW: Those screenshots were from Glyphs and as you know it's an amazing font editor.

Also, I noticed that your ligatures are wide width glyphs. That's how my glyphs used to be. There are a couple of issues with that, like caret position doesn't work inside the glyph:
![image](https://user-images.githubusercontent.com/47168/60463628-81117b00-9c1a-11e9-8a14-e81c17c26dbe.png)

Also, long chains of characters should't repeat the ligature:

Here's my Operator Mono Lig
![image](https://user-images.githubusercontent.com/47168/60463714-b7e79100-9c1a-11e9-9122-9817e2431e19.png)

Victor Mono
![image](https://user-images.githubusercontent.com/47168/60463753-ccc42480-9c1a-11e9-83cc-281dcda11643.png)

However, I dissected how Fira Code does ligatures, and it uses the Context Substitution feature to handle these issues. See https://github.com/kiliman/operator-mono-lig/issues/35 and https://github.com/kiliman/operator-mono-lig/issues/37 for more info.

Since you're actually creating the font, you can also generate the `calt` tables and add them to your font. @tonsky created a script to generate the tables https://github.com/tonsky/FiraCode/blob/master/clojure/regen_calt.clj

Thanks again for making a cool font!

**Comment by rubjo** [comment]
Hi, and thanks for the kind words + suggestions and links!

> caret position doesn't work inside the glyph

How would the caret behave inside a glyph for it to work? For me, the cursor moves one character width, regardless of it being inside a ligature glyph or not (like in your screenshot). All my ligatures' widths correspond to the number of characters they replace. Would you rather have it eg. jump over an entire three-width glyph with one keystroke?

> long chains of characters should't repeat the ligature

Maybe not, although I can't say it really matters to me. Scripts are fun, though, so I'll take a look at it at some point. :)

**Comment by tonsky** [comment]
Since I was mentioned, I might explain about “stepping inside ligature”. If you simply replace a sequence of e.g. three characters with a single glyph most of editors won’t let you step inside the ligature. It’ll just act as a one single three-width wide character. This is correct behaviour (I think).

Some editors (I think Intellij-based, but I might be mistaken) allow you to step inside no matter what font file says. This is what users want, I think.

To let users step inside ligatures in any editor, Fira Code implements a little trick: instead of replacing e.g. `-->` with a single glyph it replaces it with three glyphs: whitespace, whitespace and a ligature. Ligature itself occupies 1-char width but it overflows for two more characters to the left.

<img width="1250" alt="Screenshot 2019-07-02 at 13 33 48" src="https://user-images.githubusercontent.com/285292/60506206-0ace5080-9cce-11e9-9c0c-c1c9dfb864e1.png">

It’s a bit tricky to explain but it works. Hope that made sense and was useful.

**Comment by rubjo** [comment]
Well explained and makes perfect sense. 😄 Clever strategy for dealing with this.

I just haven't seen an editor/terminal/app so far which doesn't step inside the ligatures.

**Comment by tonsky** [comment]
Try Atom/VS Code

**Comment by kiliman** [comment]
Here's an example that shows both caret position and chained ligatures from my Operator Mono Lig font in VS Code:

![ligature-contextual-substitution](https://user-images.githubusercontent.com/47168/36854280-9a7ca4f4-1d3e-11e8-847e-519c50fb2403.gif)

**Comment by rubjo** [comment]
Ah. VS Code was fine, but after trying with Atom, I can see what you mean.

**Comment by Avi-D-coder** [comment]
I would love to try this, but I use most of the ligatures from FiraCode. Is there any chance a number of these could be included?


![](https://github.com/tonsky/FiraCode/blob/master/showcases/all_ligatures.png)

**Comment by rubjo** [comment]
A number of them *are* included. This issue is about implementing them in calt rather than liga, which might make them render/behave better in some editors.

**Comment by rubjo** [comment]
Closing this, separate issue for liga -> calt.
