### ISSUE TITLE
poor cursive italics in uppercase

### ISSUE THREAD

**Issue by traeanto** [rubjo/victor-mono#152]
i like this font, so please fix it or is there a solution for this?

![image](https://user-images.githubusercontent.com/126303616/222154552-93f52200-9f27-4338-9229-de5a10d72412.png)

**Comment by rubjo** [comment]
Hi! It looks like an issue with the terminal/app which produces this output. What are you using here?

**Comment by traeanto** [comment]
kitty 0.27.1

**Comment by rubjo** [comment]
Ah, kitty. The author has decided that this objectively "looks terrible", and would evidently prefer the rendering from your screenshot:

"When a symbol does not fit, it will either be rescaled to be smaller or truncated (depending on how much extra space it needs). This is often different from other terminals which just let the character overflow into neighboring cells, which is fine if the neighboring cell is empty, but looks terrible if it is not."

See https://sw.kovidgoyal.net/kitty/faq/#kitty-is-not-able-to-use-my-favorite-font or otherwise file an issue on that repo: https://github.com/kovidgoyal/kitty/issues
