### ISSUE TITLE
Powerline arrows (e0b0-e0b3) are misaligned vertically and don't touch the glyph borders

### ISSUE THREAD

**Issue by acid-bong** [rubjo/victor-mono#155]
![sqrt-20230708_184923](https://github.com/rubjo/victor-mono/assets/94849097/b2a090f7-308a-4685-a068-dcaa71959a60) Size 10
Note the little hanging points at the bottom, about 1 pixel long

![sqrt-20230708_184949](https://github.com/rubjo/victor-mono/assets/94849097/5ee7bea9-51d5-46cb-9ab4-5c84e879ece7) Size 15 (terminal scaled up)
The little gap of antialiasing hint between the solid text background and the arrow. Also misalignment is noticeable

![изображение](https://github.com/rubjo/victor-mono/assets/94849097/9e6321c8-7808-4755-a6b2-5fae6f24c2d0) Size 10
The images above were made in st, this one -- in Alacritty, which has a slightly larger line height. The misalignment and the hanging ends are still there. Also the top point doesn't seem to touch the top cell border

**Comment by acid-bong** [comment]
God, I'm so dumb. The solution was just to tweak the line height and the glyph offset. Hope it'll help such pedantic folks like me

**Comment by rubjo** [comment]
It’s not dumb. I’ve spent a long time myself adjusting and testing alignment and rendering of various glyphs in various apps and scenarios. Powerline glyphs are surprisingly hard to get 100% perfect in all apps and font sizes, as is evident from many other fonts as well. Glad you found something that works for you.

**Comment by Finii** [comment]
Well, there is something peculiar with the vertical metrics. I just look at the ttf variant.

Using `font-line` [1] these vertical metrics are reported:

> Baseline to basline distance: 1550
> Including a gap of: 200

<details>

```console
$ font-line report ~/Downloads/VictorMono/VictorMonoAll/TTF/VictorMono-Regular.ttf
=== /home/fini/Downloads/VictorMono/VictorMonoAll/TTF/VictorMono-Regular.ttf ===
Version 1.550
SHA1: 9bcd4916de5aaa1692b21673ae73338de3ce4535

::::::::::::::::::::::::::::::::::::::::::::::::::
  Metrics
::::::::::::::::::::::::::::::::::::::::::::::::::
[head] Units per Em:   1100
[head] yMax:           1306
[head] yMin:          -529
[OS/2] CapHeight:      800
[OS/2] xHeight:        618
[OS/2] TypoAscender:   1100
[OS/2] TypoDescender: -250
[OS/2] WinAscent:      1100
[OS/2] WinDescent:     250
[hhea] Ascent:         1100
[hhea] Descent:       -250

[hhea] LineGap:        200
[OS/2] TypoLineGap:    200

::::::::::::::::::::::::::::::::::::::::::::::::::
  Ascent to Descent Calculations
::::::::::::::::::::::::::::::::::::::::::::::::::
[hhea] Ascent to Descent:              1350
[OS/2] TypoAscender to TypoDescender:  1350
[OS/2] WinAscent to WinDescent:        1350

::::::::::::::::::::::::::::::::::::::::::::::::::
  Delta Values
::::::::::::::::::::::::::::::::::::::::::::::::::
[hhea] Ascent to [OS/2] TypoAscender:       0
[hhea] Descent to [OS/2] TypoDescender:     0
[OS/2] WinAscent to [OS/2] TypoAscender:    0
[OS/2] WinDescent to [OS/2] TypoDescender:  0

::::::::::::::::::::::::::::::::::::::::::::::::::
  Baseline to Baseline Distances
::::::::::::::::::::::::::::::::::::::::::::::::::
hhea metrics: 1550
typo metrics: 1550
win metrics:  1550

[OS/2] fsSelection USE_TYPO_METRICS bit set: True
```

</details>

If we look at the Powerline glyph `E0B0`:

![image](https://github.com/rubjo/victor-mono/assets/16012374/d33c7e88-9c90-44ae-842c-2f28d24e6af6)

The three points are at (-1, 1110); (-1, -340); (600, 385)

That means that the vertical height of that glyph is 1450. The right point is right in the middle ((1110 - 340) / 2 = 385).

So far so good. But 1450 is neither 1550 (baseline to baseline with gap) nor 1350 (pure height without counting gap).
The top seems to be matching if one assumes that the gap is always on the bottom (which it is not, some applications put it on top or half on top and half on bottom):
Ascenders = 1100, Highest point in `E0B0` = 1110 (a bit of overlap is always good with Powerline glyphs).
But the Descenders = -250, Lowest point in `E0B0` = -340.
a) Thats a bit much for overlap, and it is not symmetric top and bottom.
b) Or a bit too short if we take the gap of 200 into account: Descenders + Gap = -450; Lowest point in `E0B0` = -340

There definitively is some design issue. Which is the intended baseline to baseline distance? Does the Powerline glyphs are that same height?

Lets have a magnified look into @acid-bong's image

![image](https://github.com/rubjo/victor-mono/assets/16012374/18635ceb-9a76-4230-9865-1e56d4cdd098)

First thing to notice is that the terminal emulator **ignores** the gap value. If it would respect it the space below the `g` would be much bigger.

![image](https://github.com/rubjo/victor-mono/assets/16012374/495a14fb-5e13-4e0a-a9ed-fb571d8b382a)

As counterexample here `Xfct`, but the same is true for `Gnome Terminal`, `tilix`, `kitty` - who all respect the gap value.
Notice the different bottom below the branch icon, the bottom of the Poweline triangle, etc. Of course 'normal' apllications as `Writer` also do respect the gap.

![image](https://github.com/rubjo/victor-mono/assets/16012374/a4915f44-f4a0-4eb2-9312-61bfbac35c2f)

Interesting is also the example on the [website](https://rubjo.github.io/victor-mono/) which shows the font without the gap as very vertically condensed. Is that the intended look? But why then the gap value in the font files?

> Powerline glyphs are surprisingly hard to get 100% perfect in all apps and font sizes

Especially if you have a gap in the font instead of distributing that as 'ordinary' space to the ascenders and descenders.

My conclusion is
* Having a gap makes the baseline to baseline distance application dependent - which is problematic if some glyphs (i.e. the powerline glyphs) have to more or less match the line height.
* The existing Powerline glyphs are either too tall or too small, depending on the application's choice of 'I ignore the gap'

**Comment by rubjo** [comment]
Thanks for investingating this – these days I don't have the time to look into how this could be fixed and be sure I'm not introducing some other issues. Maybe trying the files from the Google Fonts repo (https://github.com/rubjo/victor-mono-font/releases/tag/v1.561) would help or yield different results for you.

**Comment by Finii** [comment]
Ah, the gap has been fixed here:

https://github.com/rubjo/victor-mono-font/commit/642f2f258d664d1002506fc0a614dca331042207

I could PR adapted Powerline glyphs in that repo maybe, to make it easier for you?

**Comment by rubjo** [comment]
Sure - thanks!

**Comment by Finii** [comment]
Will the changes from `victor-mono-font` be backported here, or is that the new the-real-repo?
What I mean: Which is the reference repo?

I ask because I would otherwise update Nerd Fonts to take the 1.561 font.

**Comment by rubjo** [comment]
A very good question :D The Google Fonts repo was originally made to satisfy their requirements, tests and so on (and the fact that they only accept regular or italic, not regular/oblique/italic, which is something I want to keep for the main repo, seeing as some enjoy the italics, others hate them with a passion). Along with technical requirements that were a result of me just sloppily wanting to draw a font that worked for me and not really knowing much about the process or wanting to consider hundreds of fontbakery issues.

So, now:
- this repo has the original font in three styles (as well as the web site)
- the `victor-mono-font` has a few new glyphs, along with lots of fixes and adjustments on weights, metrics etc to make GF's tests more happy

Provided I find the time, I'll probably backport most of the changes from `victor-mono-font` to here, but for now, it's probably best if you use https://github.com/rubjo/victor-mono-font/releases/tag/v1.562 for a Nerd Font PR.
