### ISSUE TITLE
Font not recognized in kitty because of missing spacing information in metadata

### ISSUE THREAD

**Issue by wimstefan** [rubjo/victor-mono#21]
First of all thank you for that beautiful font!
Would it be a big issue for you to add some spacing information?
My terminal is kitty and it does not accept fonts without the spacing information in its metadata. You can find details more here: [#486](https://github.com/kovidgoyal/kitty/issues/486) [#1372](https://github.com/kovidgoyal/kitty/issues/1372)

**Comment by rubjo** [comment]
Thanks - I’ll certainly have a look when I’m back in front of a computer in a week or so.

**Comment by rubjo** [comment]
`fc-list` reports a spacing value of 90 for Victor Mono (probably because of the way the ligatures are set up). This means that Victor Mono is not considered monospaced by `fontconfig` and probably cannot be used with kitty. This is unlikely to change in the foreseeable future.

I'm afraid you'll have to use a different font (or a terminal which is able to understand that the font is monospaced, like iTerm2).

**Comment by wimstefan** [comment]
Fair enough. Thanks anyway for a beautiful font 😏

**Comment by marioblokland** [comment]
I don't know whether there was an update on this or not. I also wasn't working for me but I have tried it again today and it is working (tested with kitty on Linux)

**Comment by rubjo** [comment]
Yes, the method for displaying ligatures was changed after this case was closed. It should all be dandy in more/most editors now. Have a beautiful weekend!

**Comment by marioblokland** [comment]
Awesome! Thanks for your work. I am going to donate for this nice font and your consistency. Have a beautiful weekend too!

**Comment by wimstefan** [comment]
The maintainer of kitty changed his policy regarding font spacing as well ... spacing=90 is allowed since this commit: https://github.com/kovidgoyal/kitty/commit/bc302dad2376ecbe014668cbba7c715b9c511211
