### ISSUE TITLE
Consider adding some more ligatures

### ISSUE THREAD

**Issue by rubjo** [rubjo/victor-mono#42]
Maybe some smoother italic-specific ones for the cases where the glyphs just about connect anyway

**Comment by tomByrer** [comment]
I find `li` hard to read.  I understand you have an increased x-height for legibility, but in the italic `i` espically when near an `l` or `t`l or the like is confusing since there is little space between the dot & body, & the top of the dot & cap height.

`<li> is very common in HTML.  Ironically it is also part of ita**li**c 

Related since I wonder if a 'left foot' ligature for the `i` could help?  A bit more larger dot &/or more vertical spacing could also.

**Comment by rubjo** [comment]
Thanks for your input.

For the next revision, I had already adjusted the i «ear». Following some initial testing, I think I’ll also increase the dot size and make it the same as the period.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sohilkaushal** [comment]
Hey sorry if I'm a bit late however compatibility with font awesome would be nice 

` <i class="fa fa-thumbs-o-up"></i>` becomes `<i class="fa fa-thumbs-o-up"></i>`

**Comment by rubjo** [comment]
@sohilkaushal Thanks for the suggestion, but I won’t be adding FA icons to this font: too much work and bloat, and I don’t really see it as that useful.

**Comment by sohilkaushal** [comment]
Yeah true although I might suggest adding a bit more docs for the project I'll be happy to help 

Cheers

**Comment by zimmah** [comment]
One ligature I'd like to see is that of the spread operator in javascript, which is three dots.

...
