### ISSUE TITLE
Bad ligature rendering for === on 13px and 14px

### ISSUE THREAD

**Issue by Eldair** [rubjo/victor-mono#73]
Ligatures === and !== are rendering badly on sizes 13px and 14px on windows (vscode)
![image](https://user-images.githubusercontent.com/470003/77529688-62ca6a00-6e90-11ea-8db0-07f95ac6967e.png)

**Comment by mariojackson** [comment]
FYI: Fira Code has the same problem in VSCode, so it might be possible that this is not only specific to Victor Mono.

**Comment by Eldair** [comment]
Yeah, others do have the same problem but it is not due to vscode since it happens on the font's website as well (in try it section)

**Comment by rubjo** [comment]
Yep, long articles and whole books are written about the differences in font rendering between Windows and other OSes. Some will say that Windows default font rendering is crappy, while others will try to find ways to defend the way it works (and they would be wrong 😛).

It boils down to this: on some font sizes (and especially more noticeably with smaller font sizes on low-DPI displays), Windows needs a lot more help (hinting) to show a character in a way which most would deem optimal.

The issue can remain here. I welcome any pull request with carefully implemented hinting, otherwise I’m more likely to spend the next few months trying to stay alive.

**Comment by mariojackson** [comment]
It's the same on a low-DPI Linux laptop though. I just tested it by using a laptop and then plugging it in on an external HiDPI display. As soon as I plug it into the external one, the problem is gone (on the external display of course) at the same font size. 

Since my MacBook has a Retina display, I can't see the stated problem there at all.
So maybe the problem only occurs in regard to low-DPI displays, like with several other fonts using ligatures.
